### ISSUE TITLE
Add fish shell compatibility

### ISSUE THREAD

**Issue by simonszu** [markeissler/gvm2#1]
One feature the "old" GVM lacks is the compatibility with the fish shell (see https://github.com/moovweb/gvm/issues/137).
If you are planning to design GVM2 like RVM, it would be great to add compatibility for the fish shell, maybe like RVM does now (https://rvm.io/integration/fish). It is mainly a manual install of RVM and a wrapper script and works great. 
I am sure the fish-and-go community would love this feature.

**Comment by markeissler** [comment]
I will take a look, I'm guessing it just needs a different installer. The GVM2 installer itself is scheduled for a re-write so this might coincide with that.

**Comment by tzapu** [comment]
any news on this one?

thank you :D

**Comment by markeissler** [comment]
I hate to say it but this isn't going to happen until I rewrite this in Go. Just achieving zsh compatibility has been a huge time commitment. I don't have a date for GVM3 right now...need to finish the zsh support in the current version first.
