### ISSUE TITLE
Best practise for contributing

### ISSUE THREAD

**Issue by javiroman** [markeissler/gvm2#2]
Is there any guide for GVM2 contributing?

I'm trying to setup GVM_ROOT=/path/to/my-forked-rep/gvm2.git in order to create new features, however I'm getting the error:

ERROR: Looks like the .git directory is present. Please reinstall GVM.

Any advises, hints?

**Comment by javiroman** [comment]
Hi @markeissler , any recommendation about it?

**Comment by markeissler** [comment]
> Is there any guide for GVM2 contributing?

Not yet. I still have some functionality upgrades planned.

> ERROR: Looks like the .git directory is present. Please reinstall GVM.

Is this a new install or are you upgrading GVM? Try renaming the `.git` file to `.git.bak`.

**Comment by javiroman** [comment]
> Is this a new install or are you upgrading GVM? Try renaming the .git file to .git.bak.

I trying to use the gvm2 cloned repository from GitHub, in order to create modifications under git control, as usual ... For that I am pointing the environment variable GVM_ROOT to this local cloned repository, I mean:

export GVM_ROOT=/home/user/dev/gvm2  ==> cloned repository from GitHub

If I move .git to .git.bak, I can not use the git commands.

Probably the best way to create modifications to GVM2 is working directly with the installed GVM2, I mean working directly with the folder installed by GVM2 ($HOME/.gvm), and copy these modifications to the cloned git repository. A dirty solution anyway!

**Comment by markeissler** [comment]
Sorry for the late response. The installer isn't ideal right now and the whole moving of `.git` to `.git.bak` is a task performed in the original installer. Actually, the original **GVM** will actually check for and rename `.git` to `.git.bak` every time a gvm command is run (IIRC).

While it's convenient to modify the in-use GVM2 it could also be problematic. One thing you might have to do is re-source the GVM commands whenever you make changes:

```sh
source "$HOME/.gvm/scripts/gvm"
```

Perhaps a better strategy for you would be to make changes in the running GVM2 and then copy those changes into a proper GVM2 repo (in another directory) if the changes are successful to what you want.

One of the ways that I develop is using a VM or docker container to avoid side effects that may be present in my own environment. The final test, of course, is the CI environment.

**Comment by markeissler** [comment]
As I close this I just want to leave this final note: it is highly likely that when I replace the gvm installer that I will move to a system where __GVM2__ is no longer installed via `git` but is instead installed as a package (tar) download. This will make updating simpler and at the same time remove unneeded commit histories from user machines.
