### ISSUE TITLE
gvm pkgenv doesn't appear to be working

### ISSUE THREAD

**Issue by skipsizemore** [markeissler/gvm2#6]
We've been working with gvm for about 18 months now, and it's proven to be a great tool. Our workflow for creating a new project has been the same for so long that I can't even remember how we came up with it: 

gvm pkgset create foo; gvm pkgenv foo; gvm pkgset use foo

The pkgenv command was necessary so that we could add the PROJECT root and bin folders to  GOROOT and GOPATH. This is so that we can use a different pkg folder for each project. gvm pkgenv has always opened an editor on a generated config file that was easily edited to add these path elements. 

With gvm2, running on High Sierra, gvm pkgenv opens on a blank file. I don't know where or how to specify my project folder. Unless I am missing something (very possible) this renders the pkgset feature fairly useless. Other than this, gvm appears to be working as it always has, and I've installed sever go versions successfully.

**Comment by markeissler** [comment]
You are correct. The command does appear to be broken. I'll have it fixed over the next few days.

**Comment by skipsizemore** [comment]
Thanks, and thanks for keeping this very useful project running.

**Comment by markeissler** [comment]
This issue has been fixed in __GVM2 0.10.4__.

To update from __v0.10.3__:
```.sh
prompt> gvm update v0.10.4
```

Then, close and re-open your terminal session.

Thanks for reporting this issue!
